import { useFetch } from '@/hooks/useFetch';
import { useBackgroundAction } from '@/hooks/useBackgroundAction';
import { command } from '@/lib/api';
import { LoadingScreen, ErrorDisplay, ModuleHeader } from '@/components/shared';
import { Markdown } from '@/components/shared/Markdown';
import { ExportButton } from '@/lib/export';
import { FileBarChart, RefreshCw, Sparkles } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';

function buildBriefingExport(b: any): string {
  let md = `# ${b.title || 'Executive Briefing'}\n\n`;
  if (b.content) md += `${b.content}\n\n`;
  const sections = [
    { title: 'Sentinel MGM', content: b.sentinelSummary },
    { title: 'YouthShield', content: b.youthShieldSummary },
    { title: 'Blight-to-Bright', content: b.blightSummary },
    { title: 'DataCenter Compass', content: b.compassSummary },
  ];
  for (const s of sections) {
    if (s.content) md += `## ${s.title}\n${s.content}\n\n`;
  }
  if (b.crossModuleInsights) md += `## Cross-Module Insights\n${b.crossModuleInsights}\n`;
  return md;
}

export default function BriefingPage() {
  const { isExecutive } = useAuth();
  const { data, loading, error, refetch } = useFetch(() => command.briefing(), []);
  const gen = useBackgroundAction('Generate Briefing', command.generateBriefing);

  const handleGenerate = () => {
    gen.execute();
    setTimeout(refetch, 3000);
  };

  if (loading) return <LoadingScreen message="Loading executive briefing..." />;
  if (error) return <ErrorDisplay error={error} onRetry={refetch} />;

  const briefing = data as any;
  const hasBriefing = briefing && briefing.title;

  return (
    <div className="space-y-6 animate-fade-in">
      <ModuleHeader
        title="Executive Briefing"
        subtitle="AI-generated weekly summary for city leadership"
        accentColor="bg-amber-500"
        icon={<FileBarChart className="w-6 h-6" />}
      >
        <div className="flex items-center gap-2">
          {hasBriefing && (
            <ExportButton
              content={buildBriefingExport(gen.data || briefing)}
              filename={`executive-briefing-${new Date().toISOString().slice(0,10)}`}
              title="Executive Briefing"
            />
          )}
          {isExecutive && (
            <button onClick={handleGenerate} disabled={gen.loading} className="btn-primary flex items-center gap-2 text-sm">
              {gen.loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              Generate New Briefing
            </button>
          )}
        </div>
      </ModuleHeader>

      {gen.loading && (
        <div className="glass-card p-8 text-center">
          <RefreshCw className="w-8 h-8 text-amber-500 animate-spin mx-auto mb-3" />
          <p className="text-slate-400">Generating executive briefing with AI...</p>
          <p className="text-xs text-slate-600 mt-1">This may take up to a minute</p>
        </div>
      )}

      {(gen.data || hasBriefing) && (
        <div className="glass-card p-8 space-y-6">
          {(() => {
            const b = gen.data || briefing;
            return (
              <>
                <div className="border-b border-slate-700/50 pb-4">
                  <h2 className="text-2xl font-display font-bold text-white">{b.title}</h2>
                  <p className="text-xs text-slate-500 mt-1">
                    Generated by {b.generatedBy} · {new Date(b.createdAt).toLocaleString()}
                  </p>
                </div>

                {b.content && (
                  <div className="prose prose-invert max-w-none print-target">
                    <Markdown>{b.content}</Markdown>
                  </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {[
                    { title: 'Sentinel MGM', content: b.sentinelSummary, color: 'border-l-sentinel-500' },
                    { title: 'YouthShield', content: b.youthShieldSummary, color: 'border-l-youthshield-500' },
                    { title: 'Blight-to-Bright', content: b.blightSummary, color: 'border-l-blight-500' },
                    { title: 'DataCenter Compass', content: b.compassSummary, color: 'border-l-compass-500' },
                  ].map(section => (
                    <div key={section.title} className={`bg-slate-800/50 rounded-xl border-l-4 ${section.color} p-5`}>
                      <h4 className="font-semibold text-white text-sm mb-2">{section.title}</h4>
                      {section.content ? <Markdown size="sm">{section.content}</Markdown> : <p className="text-slate-500 text-sm">No data available</p>}
                    </div>
                  ))}
                </div>

                {b.crossModuleInsights && (
                  <div className="bg-amber-500/5 border border-amber-500/20 rounded-xl p-5">
                    <h4 className="font-semibold text-amber-400 text-sm mb-2 flex items-center gap-2">
                      <Sparkles className="w-4 h-4" /> Cross-Module Insights
                    </h4>
                    <Markdown size="sm">{b.crossModuleInsights}</Markdown>
                  </div>
                )}
              </>
            );
          })()}
        </div>
      )}

      {!hasBriefing && !gen.data && !gen.loading && (
        <div className="glass-card p-12 text-center">
          <FileBarChart className="w-12 h-12 text-slate-600 mx-auto mb-4" />
          <h3 className="text-lg text-slate-300 font-semibold mb-2">No Briefings Generated Yet</h3>
          <p className="text-slate-500 text-sm mb-4">Generate your first executive briefing to get an AI-powered city overview</p>
          {isExecutive && (
            <button onClick={handleGenerate} className="btn-primary">
              <Sparkles className="w-4 h-4 inline mr-2" /> Generate Briefing
            </button>
          )}
        </div>
      )}
    </div>
  );
}
